import React from 'react';

const ScrollAnimation = () => {
  return (
    <div className='mt-20'>
      <div className='w-7xl mx-auto h-screen  space-y-4'>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aperiam, eligendi blanditiis officiis quos nisi! Neque nobis voluptatem sapiente ex tempora quaerat eveniet, quidem inventore soluta incidunt modi, laudantium minima? Non, molestiae animi consequuntur impedit neque eligendi doloribus debitis, pariatur, laboriosam ratione placeat. Dolorum quibusdam nulla maiores! Fugiat alias dolore ut quaerat, ex nesciunt modi maiores. Sit ratione quisquam culpa ipsum officiis perferendis, dignissimos explicabo ducimus laudantium sed nihil nesciunt illo recusandae exercitationem perspiciatis, quis facilis a voluptates voluptas expedita obcaecati numquam. In non consequatur praesentium pariatur ipsam velit sunt nobis ea! Doloremque qui voluptatum consequuntur. Molestiae obcaecati dicta cumque! Ipsam quod, perferendis maxime quos voluptatibus voluptatum neque, voluptatem doloribus sunt reprehenderit eligendi nihil maiores expedita debitis totam quam ab ea laborum distinctio nemo ipsum enim. Unde facilis commodi similique quibusdam voluptatum ratione, accusamus mollitia sequi earum doloremque repudiandae beatae, ipsum tenetur dolorem recusandae laudantium error ullam voluptas quas sint.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aperiam, eligendi blanditiis officiis quos nisi! Neque nobis voluptatem sapiente ex tempora quaerat eveniet, quidem inventore soluta incidunt modi, laudantium minima? Non, molestiae animi consequuntur impedit neque eligendi doloribus debitis, pariatur, laboriosam ratione placeat. Dolorum quibusdam nulla maiores! Fugiat alias dolore ut quaerat, ex nesciunt modi maiores. Sit ratione quisquam culpa ipsum officiis perferendis, dignissimos explicabo ducimus laudantium sed nihil nesciunt illo recusandae exercitationem perspiciatis, quis facilis a voluptates voluptas expedita obcaecati numquam. In non consequatur praesentium pariatur ipsam velit sunt nobis ea! Doloremque qui voluptatum consequuntur. Molestiae obcaecati dicta cumque! Ipsam quod, perferendis maxime quos voluptatibus voluptatum neque, voluptatem doloribus sunt reprehenderit eligendi nihil maiores expedita debitis totam quam ab ea laborum distinctio nemo ipsum enim. Unde facilis commodi similique quibusdam voluptatum ratione, accusamus mollitia sequi earum doloremque repudiandae beatae, ipsum tenetur dolorem recusandae laudantium error ullam voluptas quas sint.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aperiam, eligendi blanditiis officiis quos nisi! Neque nobis voluptatem sapiente ex tempora quaerat eveniet, quidem inventore soluta incidunt modi, laudantium minima? Non, molestiae animi consequuntur impedit neque eligendi doloribus debitis, pariatur, laboriosam ratione placeat. Dolorum quibusdam nulla maiores! Fugiat alias dolore ut quaerat, ex nesciunt modi maiores. Sit ratione quisquam culpa ipsum officiis perferendis, dignissimos explicabo ducimus laudantium sed nihil nesciunt illo recusandae exercitationem perspiciatis, quis facilis a voluptates voluptas expedita obcaecati numquam. In non consequatur praesentium pariatur ipsam velit sunt nobis ea! Doloremque qui voluptatum consequuntur. Molestiae obcaecati dicta cumque! Ipsam quod, perferendis maxime quos voluptatibus voluptatum neque, voluptatem doloribus sunt reprehenderit eligendi nihil maiores expedita debitis totam quam ab ea laborum distinctio nemo ipsum enim. Unde facilis commodi similique quibusdam voluptatum ratione, accusamus mollitia sequi earum doloremque repudiandae beatae, ipsum tenetur dolorem recusandae laudantium error ullam voluptas quas sint.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aperiam, eligendi blanditiis officiis quos nisi! Neque nobis voluptatem sapiente ex tempora quaerat eveniet, quidem inventore soluta incidunt modi, laudantium minima? Non, molestiae animi consequuntur impedit neque eligendi doloribus debitis, pariatur, laboriosam ratione placeat. Dolorum quibusdam nulla maiores! Fugiat alias dolore ut quaerat, ex nesciunt modi maiores. Sit ratione quisquam culpa ipsum officiis perferendis, dignissimos explicabo ducimus laudantium sed nihil nesciunt illo recusandae exercitationem perspiciatis, quis facilis a voluptates voluptas expedita obcaecati numquam. In non consequatur praesentium pariatur ipsam velit sunt nobis ea! Doloremque qui voluptatum consequuntur. Molestiae obcaecati dicta cumque! Ipsam quod, perferendis maxime quos voluptatibus voluptatum neque, voluptatem doloribus sunt reprehenderit eligendi nihil maiores expedita debitis totam quam ab ea laborum distinctio nemo ipsum enim. Unde facilis commodi similique quibusdam voluptatum ratione, accusamus mollitia sequi earum doloremque repudiandae beatae, ipsum tenetur dolorem recusandae laudantium error ullam voluptas quas sint.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aperiam, eligendi blanditiis officiis quos nisi! Neque nobis voluptatem sapiente ex tempora quaerat eveniet, quidem inventore soluta incidunt modi, laudantium minima? Non, molestiae animi consequuntur impedit neque eligendi doloribus debitis, pariatur, laboriosam ratione placeat. Dolorum quibusdam nulla maiores! Fugiat alias dolore ut quaerat, ex nesciunt modi maiores. Sit ratione quisquam culpa ipsum officiis perferendis, dignissimos explicabo ducimus laudantium sed nihil nesciunt illo recusandae exercitationem perspiciatis, quis facilis a voluptates voluptas expedita obcaecati numquam. In non consequatur praesentium pariatur ipsam velit sunt nobis ea! Doloremque qui voluptatum consequuntur. Molestiae obcaecati dicta cumque! Ipsam quod, perferendis maxime quos voluptatibus voluptatum neque, voluptatem doloribus sunt reprehenderit eligendi nihil maiores expedita debitis totam quam ab ea laborum distinctio nemo ipsum enim. Unde facilis commodi similique quibusdam voluptatum ratione, accusamus mollitia sequi earum doloremque repudiandae beatae, ipsum tenetur dolorem recusandae laudantium error ullam voluptas quas sint.</p>
      </div>
    </div>
  );
};

export default ScrollAnimation;